### ISSUE TITLE
Setup a react project

### ISSUE THREAD

**Issue by michaeljohannesmeier** [michaeljohannesmeier/code-exercises#1]

**Comment by michaeljohannesmeier** [comment]
Setup a new vue project:
- try by yourself to google first
- checkout https://cli.vuejs.org/guide/creating-a-project.html
- if you are not sure, checkout https://vuejs.org/
- the newly generated project should be in a foder here called: `project-1`
- push everything and assign the issue to me again

**Comment by wichofly** [comment]
I found it!

**Comment by michaeljohannesmeier** [comment]
Well done! I added a new status for the tickets. You can then set them to "In Review" and i ll close them.
