### ISSUE TITLE
Add click listener to button

### ISSUE THREAD

**Issue by michaeljohannesmeier** [michaeljohannesmeier/code-exercises#3]

**Comment by michaeljohannesmeier** [comment]
Add a click listener the the button, so that when you click the button, the number 1,2,3,... is shown (depending how often the button was clicked)

**Comment by michaeljohannesmeier** [comment]
Pull again the repo, i pushed some small changes for this task.

**Comment by michaeljohannesmeier** [comment]
ok, works., good. Put the tasks in "In Review" and not to "Done" and i ll close them when i watched them.

**Comment by wichofly** [comment]
Ohhh ok, in Review.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
