### ISSUE TITLE
Add random joke

### ISSUE THREAD

**Issue by michaeljohannesmeier** [michaeljohannesmeier/code-exercises#4]

**Comment by michaeljohannesmeier** [comment]
- Remove the button and the number, how often the button was clicked
- add axios to your dependencies in package.json (either by adding it to the package.json and then run "npm install" or by running "npm install axios"
- Add a button with text "Give me a joke"
- When pressing the button, a get request to https://api.chucknorris.io/jokes/random should be made and the joke should be displayed
- When the button is pressed again, a new joke should be displayed

**Comment by wichofly** [comment]
Hi Mike, 
I am having troubles to  fetch the API using vue. Can you check it please?

**Comment by michaeljohannesmeier** [comment]
Hey Mau,
i pushed some code. Check it out and let me know if you understand this better. Read the comments in green.

**Comment by wichofly** [comment]
Hi Mike, 
Can you please ckeck it now. 
I did it with async await when calling the API. 
I saw some examples that do not use: `setup( ){.... "all the code"....}` and at the end it is not necessary to return the functions or variables as I understand.
